### ISSUE TITLE
Color Attributes with different names.

### ISSUE THREAD

**Issue by BastianWombo** [tojynick/More-Colors#2]
Hello!

Super useful tool and congrats with the release!

Would be great to be able to select already existing color attributes. I have meshes with multiple color attributes and with different names. 
Or specify what name it should write to.

As a tip, I would shorten your extension description quite a lot. No need to explain what Islands are or when they form.
Same goes for HSV translation. You're selling the extension, not doing a tutorial. 
You already have useful tooltips in there!! Which is more than I have done for [my own extension](https://extensions.blender.org/add-ons/contextpie/) :D

great work on the addon!

**Comment by tojynick** [comment]
Heya, thanks for the suggestion! I've added support for different color attributes in _v1.1.0_, check it out!
