### ISSUE TITLE
Unable to use when only one object is in the scene

### ISSUE THREAD

**Issue by SaiZyca** [tojynick/More-Colors#3]
I'm not sure if this is a limitation or something else, but it doesn't make sense to use it this way

![image](https://github.com/user-attachments/assets/a5f7f76e-9d58-4c32-94e9-7dc23e8ac430)

**Comment by tojynick** [comment]
Hey! Just select the object. On the screenshot, nothing is selected, and the tool doesn't know what mesh it should modify.
